version: '3'
services: 
  web:
    build: . #reconoce archivo docker
    ports: 
      - "3001:3001"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: dogs
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
volumes:
  dbdata:   
  
