version: '3'
services: 
  web:
    build: . #reconoce archivo docker
    ports: 
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dbDogs
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:   
  
